export const DAFTAR_OPCODE_AUDIT = Object.freeze([
    'MOVE', 'LOADK', 'LOADBOOL', 'LOADNIL', 'GETUPVAL', 'GETGLOBAL', 'GETTABLE', 'SETGLOBAL',
    'SETUPVAL', 'SETTABLE', 'NEWTABLE', 'SELF', 'ADD', 'SUB', 'MUL', 'DIV', 'MOD', 'POW',
    'UNM', 'NOT', 'LEN', 'CONCAT', 'JMP', 'EQ', 'LT', 'LE', 'TEST', 'TESTSET', 'CALL',
    'TAILCALL', 'RETURN', 'FORLOOP', 'FORPREP', 'TFORLOOP', 'SETLIST', 'CLOSE', 'CLOSURE',
    'VARARG', 'GETIMPORT', 'FASTCALL', 'FASTCALL1', 'FASTCALL2', 'FASTCALL2K', 'JUMPIF',
    'JUMPIFNOT', 'ANDK', 'ORK', 'NAMECALL', 'DUPCLOSURE', 'CAPTURE', 'PREPVARARGS',
    'LOADB', 'GETTABLEN', 'SETTABLEN', 'GETTABLEKS', 'SETTABLEKS', 'BREAK', 'COVERAGE',
]);
